### ISSUE TITLE
Google Font

### ISSUE THREAD

**Issue by vincenzoquarta** [yithemes/yith-proteo#1]
Changing the Google Font link in Customize->Yith Theme Options it doesn't work with any font. 
It's work only with Montserrat font family.

**Comment by francgrasso** [comment]
Hi Vincenzo, thanks for reporting this issue. Can you share with me a couple of screenshots of the panel with the font inside it?
We will soon release an update of the theme with a dropdown where you can choose the font from a list, but meanwhile the manual system is working so I want to help you with it.

**Comment by vincenzoquarta** [comment]
Hi Francesco,
thanks for you reply.
I attach a screenshot with Comfortaa font link.
![Annotazione 2020-02-18 124639](https://user-images.githubusercontent.com/36382750/74733640-02bb2500-524d-11ea-9c2b-876b1ca7058a.png)
Thank you!

**Comment by francgrasso** [comment]
Hi there, meanwhile the new feature will be release, I've updated the theme documentation with instructions on how to use the current behaviour of google fonts. You can just follow this link: 
https://docs.yithemes.com/yith-proteo/customization/how-to-use-google-fonts/

**Comment by vincenzoquarta** [comment]
Thank you @francgrasso it's working fine!
