### ISSUE TITLE
'Warning: Invalid argument supplied for foreach'

### ISSUE THREAD

**Issue by maikelnay** [yithemes/yith-proteo#10]
I have this issue with the Yith-Proteo theme and i dont know how to solve it.

Thanks!

`Warning: Invalid argument supplied for foreach() in /usr/home/newyami2.com/web/wp-content/themes/yith-proteo-master/inc/customizer/custom-controls/class-google-font-select-custom-control.php on line 153 Warning: Invalid argument supplied for foreach() in /usr/home/newyami2.com/web/wp-content/themes/yith-proteo-master/inc/customizer/custom-controls/class-google-font-select-custom-control.php on line 153 Warning: Invalid argument supplied for foreach() in /usr/home/newyami2.com/web/wp-content/themes/yith-proteo-master/inc/customizer/custom-controls/class-google-font-select-custom-control.php on line 153 Warning: Invalid argument supplied for foreach() in /usr/home/newyami2.com/web/wp-content/themes/yith-proteo-master/inc/customizer/custom-controls/class-google-font-select-custom-control.php on line 153 Warning: Invalid argument supplied for foreach() in /usr/home/newyami2.com/web/wp-content/themes/yith-proteo-master/inc/customizer/custom-controls/class-google-font-select-custom-control.php on line 153 Warning: Invalid argument supplied for foreach() in /usr/home/newyami2.com/web/wp-content/themes/yith-proteo-master/inc/customizer/custom-controls/class-google-font-select-custom-control.php on line 153 Warning: Invalid argument supplied for foreach() in /usr/home/newyami2.com/web/wp-content/themes/yith-proteo-master/inc/customizer/custom-controls/class-google-font-select-custom-control.php on line 153 Warning: Invalid argument supplied for foreach() in /usr/home/newyami2.com/web/wp-content/themes/yith-proteo-master/inc/customizer/custom-controls/class-google-font-select-custom-control.php on line 153 Warning: Invalid argument supplied for foreach() in /usr/home/newyami2.com/web/wp-content/themes/yith-proteo-master/inc/customizer/custom-controls/class-google-font-select-custom-control.php on line 153 Warning: Invalid argument supplied for foreach() in /usr/home/newyami2.com/web/wp-content/themes/yith-proteo-master/inc/customizer/custom-controls/class-google-font-select-custom-control.php on line 153 Warning: Invalid argument supplied for foreach() in /usr/home/newyami2.com/web/wp-content/themes/yith-proteo-master/inc/customizer/custom-controls/class-google-font-select-custom-control.php on line 153`

**Comment by francgrasso** [comment]
Hi there,
issue fixed!
Thanks for reporting :)

**Comment by maikelnay** [comment]
Thanks!!!
