### ISSUE TITLE
It is not really an issue

### ISSUE THREAD

**Issue by adrianvignolo** [yithemes/yith-proteo#11]
Hi, I was looking to communicate with you because I have a question.
 I would like to know if you are going to update the code to work with a more recent version of fontawesome?
 If it is positive and if it helps I've pushed the old version of Yith that I have where I updated the files to work with a more recent version of fontawesome.

Thanks. I also hope I can help.

**Comment by francgrasso** [comment]
Hi there,
I'm sorry but Proteo is not integrating FontAwesome... also I cannot see anly pull request from you on Proteo project.
Maybe you are referring to another topic? like YITH Wishlist?
If yes, please open you issue there :)

**Comment by adrianvignolo** [comment]
Yes, sorry. I am talking about wishlist. I am going to check. I remember
puahing some changes somewhere. Where should I let wishlist developers know?

**Comment by francgrasso** [comment]
Sure, no problem, the link is: https://github.com/yithemes/yith-woocommerce-wishlist

I'm setting this issue as solved then :)
