### ISSUE TITLE
[yith-slider-for-page-builders] - Wrong class for slider container

### ISSUE THREAD

**Issue by domegang** [yithemes/yith-proteo#13]
I changed the "Slider content max width" from wp admin without any effect.
The plugin generate a wrong class name for  the slider-container.
<img width="1653" alt="" src="https://user-images.githubusercontent.com/3818926/102766994-3be98780-437f-11eb-9abc-462e2d8f6734.png">

L149 on templates/shortcodes/yith-slider.php

**Comment by francgrasso** [comment]
Hi there!
Thanks for reporting it!
I will send an update to fix it

**Comment by francgrasso** [comment]
version 1.0.4 just released. https://wordpress.org/plugins/yith-slider-for-page-builders/
