### ISSUE TITLE
IT_it Translation "Uppercase" should be "Maiuscolo"

### ISSUE THREAD

**Issue by EugenioPetulla** [yithemes/yith-proteo#15]
https://github.com/yithemes/yith-proteo/blob/9b41b1b145701d8ae73ec8fff7ee96fddd318b9d/languages/yith-proteo-it_IT.po#L1441

The issue title is self-explanatory :D

**Comment by francgrasso** [comment]
Thank you! I will change it also on translate.wordpress.org

**Comment by francgrasso** [comment]
Fixed with commit 9b4ce0430188214b47d724a43652cfeab32d4dfa
