### ISSUE TITLE
widget_yith_proteo_account_widget icon is an img

### ISSUE THREAD

**Issue by EugenioPetulla** [yithemes/yith-proteo#17]
Actually is impossible to dinamically change the color of this icon because it's an img tag and the only manipulatoin we can apply is a ```filter``` property, not the ideal use case here.

https://github.com/yithemes/yith-proteo/blob/6c63ce5d88c641f2e8840dd48391b41bf706fc04/inc/widgets/class-yith-proteo-account-widget.php#L60

I suggest to change the icon with the font-icon version or just inject the full SVG code in the HTML so we can use the ```fill``` css property in order to dinamically change the color according to the selected theme option.

Ref: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Fills_and_Strokes#using_css

Actual issue example here:

![menu-issue-1](https://user-images.githubusercontent.com/3589467/115041530-e6f3f300-9ed2-11eb-98eb-4fe1a619a660.jpg)

**Comment by francgrasso** [comment]
Hi there,
issue fixed with commit https://github.com/yithemes/yith-proteo/commit/fc828f5748e41acd59127ebc5d9d411f87330110

**Comment by francgrasso** [comment]
Please provide feedback in order to close this issue 👍

**Comment by EugenioPetulla** [comment]
Fix tested and confirmed! :D
