### ISSUE TITLE
Page Templates & Documentation

### ISSUE THREAD

**Issue by 50North4West** [yithemes/yith-proteo#2]
Hi.

Is there any documentation available with how to set-up the theme to look and feel like the demo? Your documentation is missing?

I don't seem to have any page templates?

**Comment by francgrasso** [comment]
Hi there,
about theme documentation you are totally right. The documentation will be completed and improved this week with all theme options and also with the structure of each page of our live demo.

We are constantly improving this theme, and we have also released the slider plugin (for free) which is used in our live demo. You can find it here: https://wordpress.org/plugins/yith-slider-for-page-builders/

I hope you will be enthusiast of this theme while using it and you can wait a little to have all you need.
