### ISSUE TITLE
Trying to get property 'ID' of non-object 

### ISSUE THREAD

**Issue by Mte90** [yithemes/yith-proteo#20]
We got some errors `yith-proteo/inc/template-functions.php on line 262` I think on 404 pages.

**Comment by Mte90** [comment]
Yes that function https://github.com/yithemes/yith-proteo/blob/master/inc/template-functions.php#L262 doesn't check if the post exists.

**Comment by francgrasso** [comment]
Thanks, will fix in coming commits

**Comment by Mte90** [comment]
any updates?

**Comment by francgrasso** [comment]
On 404 pages I don't have the error. Is this report still valid? 
https://prnt.sc/200fuw2
If yes, can you please share a link with the issue or add steps to replicate it?
Thanks
