### ISSUE TITLE
Obsolete CSS proprierties

### ISSUE THREAD

**Issue by Mte90** [yithemes/yith-proteo#23]
As example:
```
flex-direction: column;
-webkit-flex-direction: column;
```

https://caniuse.com/?search=flex-direction
Flex direction is supported by chrome 29/2013 without the prefix

Also with the rest of flexbox proprierties

Like also for
```
-webkit-transition: 0.25s ease;
    -moz-transition: 0.25s ease;
    -o-transition: 0.25s ease;
    transition: 0.25s ease;
```

Also for
```
 -webkit-box-shadow: -2px 2px 81px -27px rgba(0, 0, 0, 0.29);
```

Remove this stuff can save space on the css file.

**Comment by francgrasso** [comment]
fixed in 0b1ebd8aca0f657a35717088cd5b5f9e774a473b
