### ISSUE TITLE
Incompatibility: gridlist-view-for-woocommerce (by BeRocket)

### ISSUE THREAD

**Issue by ADIAProject** [yithemes/yith-proteo#32]
Hello. After the update, there was an incompatibility between the latest release of the theme and the plugin 
https://ru.wordpress.org/plugins/gridlist-view-for-woocommerce/

The catalog display breaks, the settings for the number of products and lines do not work.
I did not find similar functionality among your plugins.
Perhaps this change is affecting, but I did not understand how to use it 
"Tweak: migrate css products list layout from float and flex to grid"

**Comment by francgrasso** [comment]
Hi there, thanks for reporting.
The product count is working fine, the only issue is related to the LIST layout. I will work to add support to this plugin

**Comment by francgrasso** [comment]
hei @ADIAProject can you please share a link or a screenshot about how the list layout should appear?
Thanks

**Comment by ADIAProject** [comment]
Hi. I have not rolled back to the old version of the theme. Therefore, I cannot show how it looked qualitatively.
But there are several photos taken with the phone: 
[https://водопроводов.рф/screens/yithproteo-berocket_1.jpg](url)
[https://водопроводов.рф/screens/yithproteo-berocket_2.jpg](url)

**Comment by francgrasso** [comment]
Hi there,
please check commit 487b81c. It should work as before the last theme update

**Comment by ADIAProject** [comment]
Hi. Francesco, thanks a lot, now everything looks great !!!

P.S. It would be nice if you had this functionality native to the theme :)

**Comment by francgrasso** [comment]
Thanks! I will propose it ;) I'm closing the issue, fill free to open a new one if needed
