### ISSUE TITLE
Some issues with Safari

### ISSUE THREAD

**Issue by nknov** [yithemes/yith-proteo#4]
Great Theme. Thanks for the work.
I've downloaded the latest master from this GitHub and I found a few issues with Safari
(1) On Safari the Comments in sidebar doesn't render on normal view. It only renders in Customizer view. They render fine on firefox and chrome and don't have this issue.
(2) On Safari, the search button bleeds into right side if sidebar is on left. If sidebar is on right the search button works fine. However, if you zoom out it renders fine on safari. On firefox and chrome this works all right.
(3) Failed to load resource: the server responded with a status of 404 (Not Found) for themes/yith-proteo/bootstrap-grid.css.map in Safari

**Comment by francgrasso** [comment]
Hi there
1) https://prnt.sc/tdxhtg I tested the website and was not able to reproduce the issue. Can you share we me a url to check?
2) thanks for reporti. Will add a fix in the coming release
3) Will fix it too in the coming release

**Comment by francgrasso** [comment]
I haven't had any more news from you. So I'm setting this issue closed
