### ISSUE TITLE
Contact form 7 error visible upon site loading

### ISSUE THREAD

**Issue by design311** [yithemes/yith-proteo#5]
The notification system for Proteo seems to show the Contact Form 7 alert element for a short period of time when loading the site.

The element in question:
`<div class="wpcf7-response-output" role="alert" aria-hidden="true"></div>`

Screenshot:
![image](https://user-images.githubusercontent.com/4565650/86651938-dde90380-bfdb-11ea-9dc0-836dcb51eafc.png)

**Comment by francgrasso** [comment]
Thanks for your reporting. Will fix it in the coming release!
