### ISSUE TITLE
Content container is being pushed down, causing a layout shift

### ISSUE THREAD

**Issue by design311** [yithemes/yith-proteo#6]
It seems that the content container for the whole site is dynamically getting a `padding-top` as a result, the whole website is getting flagged by Google for not passing the Core Web Vitals.

The element in question:
`<div id="content" class="site-content" style="padding-top: 124px;">`

The result:
![image](https://user-images.githubusercontent.com/4565650/86662968-2658ef00-bfe5-11ea-9403-01176732b926.png)

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fproteo.yithemes.com%2Fclassic-shop%2F&hl=en_GB

**Comment by francgrasso** [comment]
Hi there,
the dinamic padding is needed for the sticky header feature. Disabling it, the issue is not happening

**Comment by francgrasso** [comment]
I haven't had any more news from you. So I'm setting this issue closed
