### ISSUE TITLE
Buttons orders page on mobile device out of screen

### ISSUE THREAD

**Issue by apeacenl** [yithemes/yith-proteo#7]
Hi,

I found an issue on the orders page in the frontend. The table is not fully showable on a mobile screen, causing the buttons to only show for about 50%.

I've attached a screenshot of it.

Thanks,

Neal
![IMG_3823](https://user-images.githubusercontent.com/68231326/87309811-61937a80-c51d-11ea-8cfb-9ea4fcc52f49.PNG)

**Comment by francgrasso** [comment]
fixed in commit nr 75e5784
