### ISSUE TITLE
Terms and conditions are being shortened on checkout page

### ISSUE THREAD

**Issue by mklasen** [yithemes/yith-proteo#9]
Woocommerce runs the `woocommerce_short_description` over the terms and conditions that are displayed on the checkout page. The `yith_proteo_limit_woocommerce_short_description` function is hooked into this filter. This results in only showing the first 40 words from the Terms and conditions page.

I've created a PR with a fix here: https://github.com/yithemes/yith-proteo/pull/8

**Comment by francgrasso** [comment]
Thank you for the kind reporting. Pull request merged!
